rails 3.2 and ruby 1.9.3 initial changes
mysql2 needs to increase in order to work on rails 3.1 and higher.
use patched calendar_date_select
  the official calendar_date_select uses RAILS_ROOT which doesn't exist in rails 3.2
add prototype-rails, disable debug_rjs
  it seems debug_rjs should still work based on readme:
  https://github.com/rails/prototype-rails
  But instead an error is thrown, this looks like a bug in prototype-rails.
  Here is my bug report:
  https://github.com/rails/prototype-rails/issues/10
class_inheritable_array is no longer available
  this page has info:
  http://apidock.com/rails/Class/class_attribute
  http://guides.rubyonrails.org/active_support_core_extensions.html
  Note this fix doesn't work the same way as the original so the usage of role_requirements
    needs to be checked. It actually appears it is not used anymore.
bump database_cleaner to fix error when running tests
  this was the error:
  superclass mismatch for class Mysql2Adapter (TypeError)
  /Users/scytacki/.rvm/gems/ruby-1.9.3-p125@rigse/gems/database_cleaner-0.6.7/lib/database_cleaner/active_record/truncation.rb:31:in `<module:ConnectionAdapters>'
bump themes_for_rails version to remove warnings
bump version of testing libraries
Change approach for checking ActiveRecord connection
switch prototype_legacy_helper to pickup 3.1 changes
replace calls to Given/When/Then with "step"
  this removes deprecation warning from cucumber
Use the cucumber-rails javascript_strategy section
  by setting javascript_strategy to transaction we can gain a little speed.
  this works by limiting AR to one DB connection so both the test thread
  and the server thread use the same DB connection and thus the same
  transaction.
update mock installation into cucumber
  https://github.com/cucumber/cucumber/wiki/Mocking-and-Stubbing-with-Cucumber
  without this there is a cryptic error:
  undefined method `expectation_ordering' for nil:NilClass
  which occurs because the RSpec::Mocks::setup method wasn't called
fix issues with deep_cloning in rails 3.2
  the attributes_from_column_definition method was removed
  the semantics of clone was changed so now the appropriate method
  seems to be dup instead
FlashHash#each_pair is no longer supported - FlashHash#each does the same thing
update our custom haml fork with rails 3.2 fixes from upstream
bump ci_reporter
update fails_in_themes for latest rspec
remove rack_hotfix now that we are up to v 1.3
use debugger instead of ruby-debug19
lock spreadsheet gem to earlier version to avoid non backwards compatible change