update mock installation into cucumber
https://github.com/cucumber/cucumber/wiki/Mocking-and-Stubbing-with-Cucumber
without this there is a cryptic error:
undefined method `expectation_ordering' for nil:NilClass
which occurs because the RSpec::Mocks::setup method wasn't called