fix: config/initializers/rites.rb error handling
This seems to be working now.

JRuby throws a RuntimeError

RuntimeError: The driver encountered an error: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown database 'rites_development'

MRI throws a Mysql::Error. Unfortunately Mysql::Error
isn't defined as a constant until after the ActiveRecord
statement that causes the error.

But Mysql::Error inherits from StandardError so that will do.

  Mysql::Error.ancestors
  => [Mysql::Error, StandardError, ...