Hmn,
Suddenly the import task stopped working with this exception:

undefined method `grade_span LIKE '%9-11%'=' for
/web/rites.concord.org/releases/20090402164932/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:255:in
`method_missing'

which was happening on lione 292 in lib/parser.rb
Huh.