Fix initial test in git_repo_info helper.
Using && doesn't work here -- in the second assignment 
the local variable: repo is nil.

Examples:

  This doesn't work:

  >> a = 1 && b = a + a
  NoMethodError: You have a nil object when you didn't expect it!

  This does:

  >> a = 1 and b = a + a
  => 2