Fix cucumber test "abstract_class?" bug.
Like the rspec tests, the cucumber tests were failing while using the dynamic finder "find_by_login" (throwing: "undefined method `abstract_class?' for Object:Class (NoMethodError)").  Luckily, these finders were only used in the step definitions, so I could just update them to use "User.first(:conditions => { :login => ... })" instead, which fixes the bug.